### ISSUE TITLE
Allow Custom "Run Test" Directive

### ISSUE THREAD

**Issue by tomdeering-wf** [Workiva/goverge#20]
Projects may sometimes wish to kick off their tests for coverage measurement in a custom way. For example, github.com/Workiva/linking-benchmark has some Go linker magic that sets the values of in-code constants at build time, and these constants are required for some tests to pass. For the time being we're forced to (i) not use goverge, or (ii) disable those assertions that depend on the constants.

It would be a nice enhancement if goverge accepted an arbitrary, custom command to kick off tests. This would address most conceivable use cases where tests need to be run with some custom options.

**Comment by wesleybalvanz-wf** [comment]
This was handle with this PR: https://github.com/Workiva/goverge/pull/21 closing
